### PR TITLE
Added local server setup to `installation` section

### PR DESCRIPTION
**Pull request by LuMarans30**
I've added a new section to the installation guide that provides step-by-step commands for running the proxy with a local server, specifically llama.cpp.

### CODE REVIEW

**Comment by codelion** [comment]
This looks good, but are you sure [llama-cpp-python](https://github.com/abetlen/llama-cpp-python). supports multiple responses using the `n` param ? I think it has the same limitation as the llama-server as it is just a wrapper around it.

**Comment by codelion** [comment]
This PR fixes #8.

**Comment by LuMarans30** [comment]
> This looks good, but are you sure [llama-cpp-python](https://github.com/abetlen/llama-cpp-python). supports multiple responses using the `n` param ? I think it has the same limitation as the llama-server as it is just a wrapper around it.

Sorry, my bad. I misread the message and thought it was a merged PR.

**Comment by codelion** [comment]
@LuMarans30 I recently added a CLA, can you please sign it here - https://cla-assistant.io/codelion/optillm

**Comment by LuMarans30** [comment]
> @LuMarans30 I recently added a CLA, can you please sign it here - https://cla-assistant.io/codelion/optillm

Done, signed the CLA.

**Comment by codelion** [comment]
Thank you!

**Pull request merged**
